# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/cncImportUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(513, 590)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.info_txt = QtWidgets.QLabel(Dialog)
        self.info_txt.setObjectName("info_txt")
        self.verticalLayout.addWidget(self.info_txt)
        self.txt_cnc = QtWidgets.QPlainTextEdit(Dialog)
        self.txt_cnc.setObjectName("txt_cnc")
        self.verticalLayout.addWidget(self.txt_cnc)
        self.tab_para = QtWidgets.QTableWidget(Dialog)
        self.tab_para.setAlternatingRowColors(True)
        self.tab_para.setObjectName("tab_para")
        self.tab_para.setColumnCount(1)
        self.tab_para.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tab_para.setHorizontalHeaderItem(0, item)
        self.tab_para.horizontalHeader().setDefaultSectionSize(50)
        self.tab_para.horizontalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.tab_para)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.but_back_close = QtWidgets.QPushButton(Dialog)
        self.but_back_close.setObjectName("but_back_close")
        self.horizontalLayout_2.addWidget(self.but_back_close)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.but_accept = QtWidgets.QPushButton(Dialog)
        self.but_accept.setObjectName("but_accept")
        self.horizontalLayout_2.addWidget(self.but_accept)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.info_txt.setText(_translate("Dialog", "Hier steht dann ein Lauftext."))
        self.txt_cnc.setPlainText(_translate("Dialog", "Texteditor\n"
""))
        item = self.tab_para.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Test"))
        self.but_back_close.setText(_translate("Dialog", "Close"))
        self.but_accept.setText(_translate("Dialog", "Accept"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
