# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/errorDialogueUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(216, 146)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.icon = QtWidgets.QLabel(Dialog)
        self.icon.setMinimumSize(QtCore.QSize(60, 60))
        self.icon.setMaximumSize(QtCore.QSize(60, 60))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap(":/err/warning.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.horizontalLayout_2.addWidget(self.icon)
        self.message = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message.sizePolicy().hasHeightForWidth())
        self.message.setSizePolicy(sizePolicy)
        self.message.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.message.setWordWrap(True)
        self.message.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.message.setObjectName("message")
        self.horizontalLayout_2.addWidget(self.message)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setObjectName("formLayout")
        self.lab_ang = QtWidgets.QLabel(Dialog)
        self.lab_ang.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_ang.setObjectName("lab_ang")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lab_ang)
        self.par_ang = QtWidgets.QDoubleSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.par_ang.sizePolicy().hasHeightForWidth())
        self.par_ang.setSizePolicy(sizePolicy)
        self.par_ang.setMinimumSize(QtCore.QSize(60, 0))
        self.par_ang.setWrapping(False)
        self.par_ang.setFrame(False)
        self.par_ang.setAlignment(QtCore.Qt.AlignCenter)
        self.par_ang.setReadOnly(False)
        self.par_ang.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.par_ang.setSpecialValueText("")
        self.par_ang.setAccelerated(False)
        self.par_ang.setProperty("showGroupSeparator", False)
        self.par_ang.setPrefix("")
        self.par_ang.setSuffix("")
        self.par_ang.setSingleStep(0.05)
        self.par_ang.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.par_ang.setObjectName("par_ang")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.par_ang)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.but_back = QtWidgets.QPushButton(Dialog)
        self.but_back.setObjectName("but_back")
        self.horizontalLayout.addWidget(self.but_back)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.but_ok = QtWidgets.QPushButton(Dialog)
        self.but_ok.setObjectName("but_ok")
        self.horizontalLayout.addWidget(self.but_ok)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.message.setText(_translate("Dialog", "Placeholder text for error message"))
        self.lab_ang.setText(_translate("Dialog", "New increment"))
        self.but_back.setText(_translate("Dialog", "Abort"))
        self.but_ok.setText(_translate("Dialog", "OK"))
import icns_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
