# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/trimgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(551, 438)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plotwidget = MplWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotwidget.sizePolicy().hasHeightForWidth())
        self.plotwidget.setSizePolicy(sizePolicy)
        self.plotwidget.setObjectName("plotwidget")
        self.verticalLayout.addWidget(self.plotwidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.but_trim_left = QtWidgets.QPushButton(Dialog)
        self.but_trim_left.setObjectName("but_trim_left")
        self.horizontalLayout.addWidget(self.but_trim_left)
        self.slider_left = QtWidgets.QSlider(Dialog)
        self.slider_left.setOrientation(QtCore.Qt.Horizontal)
        self.slider_left.setObjectName("slider_left")
        self.horizontalLayout.addWidget(self.slider_left)
        self.slider_right = QtWidgets.QSlider(Dialog)
        self.slider_right.setOrientation(QtCore.Qt.Horizontal)
        self.slider_right.setObjectName("slider_right")
        self.horizontalLayout.addWidget(self.slider_right)
        self.but_trim_right = QtWidgets.QPushButton(Dialog)
        self.but_trim_right.setObjectName("but_trim_right")
        self.horizontalLayout.addWidget(self.but_trim_right)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.but_trim_left.setText(_translate("Dialog", "TRIM LEFT"))
        self.but_trim_right.setText(_translate("Dialog", "TRIM RIGHT"))
from gui.mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
